name: Predator Daily Auto-Update

on:
  schedule:
    - cron: '30 0 * * *' # 台北 08:30
    - cron: '30 8 * * *' # 台北 16:30
  workflow_dispatch:

jobs:
  market-analysis: # 對應您的 job 名稱
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit pandas yfinance matplotlib requests beautifulsoup4
          # 如果你有 requirements.txt，也可以用 pip install -r requirements.txt

      - name: Run Stock Analysis
        run: python main.py --market tw-share

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add global_market_summary.csv || echo "No changes to add"
          git commit -m "Auto-update market data" || echo "No changes to commit"
          git push
