name: Predator Daily Auto-Update
on:
  schedule:
    - cron: '30 0 * * *' # 台北 08:30
    - cron: '30 8 * * *' # 台北 16:30
  workflow_dispatch:

jobs:
  market-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install streamlit pandas yfinance matplotlib requests beautifulsoup4 flask

      - name: Run Stock Analysis
        run: python main.py --market tw-share

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add global_market_summary.csv || echo "No changes"
          git commit -m "Auto-update market data" || echo "No changes"
          git push
